### PR TITLE
Updates ACL style files from 2019 to 2020

### PR DESCRIPTION
**Pull request by bethard**
Thanks to @davidweichiang for letting the ACL 2020 publication chairs (myself, @ryancotterell, and Rui Yan) know about this repository.

This is just blindly committing [what is being distributed for ACL 2020](http://acl2020.org/downloads/acl2020-templates.zip). The .sty file changes were all blindly inherited from the ACL 2019 template on Overleaf, so the changes there may or may not be desirable. The .tex changes are intentional; we did a major restructuring to make sure that important points were better highlighted than in the past, and we restructured the Word template to match. The .zip file and the [overleaf template](https://www.overleaf.com/latex/templates/acl-2020-proceedings-template/zsrkcwjptpcd) both also included `anthology.bib`, which I did not include in this pull request because of its size, but if you think that belongs here too, I can add it.

It's too late to make any changes for ACL 2020, but if there are improvements (e.g., @davidweichiang said that these templates are supposed to no longer produce `Submission ***` since START can do that directly) maybe they can be committed on top of the changes here?

### CODE REVIEW

**Comment by davidweichiang** [comment]
Thanks! I see a lot of improvements but also a few regressions besides the "Submission **" thing (80fa3f0b0baca0aecc5355e83552e0a432a6e3b2, maybe 6297bba02ccc7cc28b5bccac446031e2e7f91bef, 69a334154785f68b5b71a116d19feb0cacc5a461, 9b8b413a4f1ca46d51813d1471a796f2e6e919ae). What would be the best way to merge these?

**Comment by bethard** [comment]
Yeah, kinda depends on how much history people want to keep in this repository. I agree that all the changes you identified as regressions look like things that should be restored. I'm still not sure who's in charge of this repo, but I would lean towards simply adding an additional commit to this pull request that reapplies those changes. That would let commit 92914f9 be tagged as ACL 2020, while also making it clear what was intended for future conferences.

**Comment by mjpost** [comment]
Thanks for this, @bethard! Retaining the changes should be as simple as merging the latest acl-org:gh-pages into your branch, no?

**Comment by davidweichiang** [comment]
I think that's what @bethard is proposing, which I think would be best; doing a `git cherry-pick` on the commits I listed should do it, I think. Maybe https://github.com/acl-org/acl-pub/commit/9b8b413a4f1ca46d51813d1471a796f2e6e919ae would not work automatically because the instructions have been reordered.

I'm unsure what to do about the (really annoying) hyperref page-break problem. It appears that there are two fixes, one from @strubell and @danielgildea (https://github.com/acl-org/acl-pub/commit/6297bba02ccc7cc28b5bccac446031e2e7f91bef) and one from @bethard and co-chairs, and I have no idea if they are compatible.

**Comment by davidweichiang** [comment]
This will close #7

**Comment by bethard** [comment]
Any changes to the .sty here are not from me or my co-chairs; they're from the ACL 2019 Overleaf template. So I have no opinion on which solution is preferred, and am happy to take whichever path a more informed developer suggests.

**Comment by danielgildea** [comment]
On Wed, November 13, 2019 at  7:17PM, David Chiang wrote:
> I'm unsure what to do about the (really annoying) hyperref page-break problem. It appears that there are two fixes, one from @strubell and @danielgildea (https://github.com/acl-org/acl-pub/commit/6297bba02ccc7cc28b5bccac446031e2e7f91bef) and one from @bethard and co-chairs, and I have no idea if they are compatible.

Hi,

The two fixes for hyperref are for different issues, and are not incompatible.

The fix from Emma Strubell is for dvi-producing latex only.  Generally
people should not be using dvi-producing latex, but it can happen
if you are not carefull when uploading to arxiv.

The etoolbox fix does not work with the latest version of latex:
https://tex.stackexchange.com/questions/487428/patch-failed-in-emnlp-style-template
so I do not think we should include it in the repository.  The
underlying problem will eventually get fixed as people update
their latex distributions.

Dan

**Comment by davidweichiang** [comment]
Thanks @bethard and @danielgildea. I think what would yield the cleanest history would be:

1. @bethard cherry-picks the commits listed above into his branch
2. I think I can merge the PR; if not, maybe @danielgildea can
3. If not already, I can revert the etoolbox fix and push

If cherry-pick doesn't work (because the commits are already in the history), then I can just go through and make a new commit that resolves everything.

**Comment by bethard** [comment]
I've cherry-picked as appropriate, though the last one couldn't be cherry-picked since it applied to the NAACL file instead of the ACL one, so I copied the changes by hand. I also manually removed the etoolbox workaround in the .sty file, but haven't updated the .tex file accordingly under `\section{\LaTeX{} Compilation Issues}` since I wasn't sure what it should say. Hopefully one of you can adjust that appropriately.

**Comment by davidweichiang** [comment]
Thanks! I'll see what I can do from here.

**Pull request merged**
